[package]
name = "tracert"
version = "0.1.0"
authors = ["Pam <pamhome21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.37"
json = "0.12.4"
regex = "1.5.4"
clap = "2.33.3"